version: '3.7'

services:
  memento-frontend:
    container_name: memento-frontend
    tty: true
    stdin_open: true
    build:
      context: frontend
      dockerfile: 'Dockerfile'
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  memento-backend:
    depends_on:
        - migrate
    container_name: memento-backend
    tty: true
    stdin_open: true
    restart: always
    build:
      context: backend
      dockerfile: 'Dockerfile'
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    ports:
      - 4000:4000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: 'db'
    command: ["./wait-for-it.sh" , "db:3306" , "--strict" , "--timeout=300" , "--", "nodemon", "server"]
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: memento
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
  migrate:
    container_name: migrate
    tty: true
    stdin_open: true
    build:
      context: db
      dockerfile: 'Dockerfile'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: 'jdbc:mysql://db:3306/memento'
    command: ["./wait-for-it.sh" , "db:3306" , "--strict" , "--timeout=300" , "--", "flyway", "migrate"]
